// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package WebServiceExtension.com.owfg.stub;


public class Banner {
    protected long bannerId;
    protected java.lang.String bannerName;
    
    public Banner() {
    }
    
    public Banner(long bannerId, java.lang.String bannerName) {
        this.bannerId = bannerId;
        this.bannerName = bannerName;
    }
    
    public long getBannerId() {
        return bannerId;
    }
    
    public void setBannerId(long bannerId) {
        this.bannerId = bannerId;
    }
    
    public java.lang.String getBannerName() {
        return bannerName;
    }
    
    public void setBannerName(java.lang.String bannerName) {
        this.bannerName = bannerName;
    }
}
