// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.owfg.stub;


public class GetActiveStoresResponse {
    protected com.owfg.stub.Store[] stores;
    
    public GetActiveStoresResponse() {
    }
    
    public GetActiveStoresResponse(com.owfg.stub.Store[] stores) {
        this.stores = stores;
    }
    
    public com.owfg.stub.Store[] getStores() {
        return stores;
    }
    
    public void setStores(com.owfg.stub.Store[] stores) {
        this.stores = stores;
    }
}
