// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.owfg.stub;


public class GetActiveStoresResponse {
    protected com.owfg.stub.Store[] _return;
    
    public GetActiveStoresResponse() {
    }
    
    public GetActiveStoresResponse(com.owfg.stub.Store[] _return) {
        this._return = _return;
    }
    
    public com.owfg.stub.Store[] get_return() {
        return _return;
    }
    
    public void set_return(com.owfg.stub.Store[] _return) {
        this._return = _return;
    }
}
