// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.owfg.stub;


public class GetBannersResponse {
    protected com.owfg.stub.Banner[] _return;
    
    public GetBannersResponse() {
    }
    
    public GetBannersResponse(com.owfg.stub.Banner[] _return) {
        this._return = _return;
    }
    
    public com.owfg.stub.Banner[] get_return() {
        return _return;
    }
    
    public void set_return(com.owfg.stub.Banner[] _return) {
        this._return = _return;
    }
}
