// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.owfg.stub;


public class GetStoreManagementInfoResponse {
    protected com.owfg.stub.StoreManagementInfo _return;
    
    public GetStoreManagementInfoResponse() {
    }
    
    public GetStoreManagementInfoResponse(com.owfg.stub.StoreManagementInfo _return) {
        this._return = _return;
    }
    
    public com.owfg.stub.StoreManagementInfo get_return() {
        return _return;
    }
    
    public void set_return(com.owfg.stub.StoreManagementInfo _return) {
        this._return = _return;
    }
}
