// This class was generated by 172 StubGenerator.
// Contents subject to change without notice.
// @generated

package com.owfg.stub;

public interface StoreManagement extends java.rmi.Remote {
	public com.owfg.stub.Store[] getActiveStores() throws java.rmi.RemoteException;

	public com.owfg.stub.Banner[] getBanners() throws java.rmi.RemoteException;

	public com.owfg.stub.ItemSalesHistoryInfo[] getItemSalesHistory(long storeId, java.lang.String upc) throws java.rmi.RemoteException;

	public com.owfg.stub.StoreManagementInfo getStoreManagementInfo(long storeId, java.lang.String upc) throws java.rmi.RemoteException;

}
